services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["${RABBITMQ_PORT}:5672", "15672:15672"]
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping && bash -lc '</dev/tcp/127.0.0.1/5672'" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
      
  main-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports: [ "5432:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s
  
  name-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: name
    ports: [ "5433:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  surname-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surname
    ports: [ "5434:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s
  
  main:
    build: ./main
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__postgres=Host=main-db;Port=5432;Database=main;Username=postgres;Password=postgres
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_Audience}
      - RabbitMQOptions__Host=rabbitmq
      - RabbitMQOptions__Port=${RABBITMQ_PORT}
      - RabbitMQOptions__Username=${RABBITMQ_USER}
      - RabbitMQOptions__Password=${RABBITMQ_PASS}
    ports: ["5001:8080"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      main-db:
        condition: service_healthy
      
  name:
    build: ./name
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__postgres=Host=name-db;Port=5432;Database=name;Username=postgres;Password=postgres
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_Audience}
      - RabbitMQOptions__Host=rabbitmq
      - RabbitMQOptions__Port=${RABBITMQ_PORT}
      - RabbitMQOptions__Username=${RABBITMQ_USER}
      - RabbitMQOptions__Password=${RABBITMQ_PASS}
    ports: ["5002:8080"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      name-db:
        condition: service_healthy
        
  surname:
    build: ./surname
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__postgres=Host=surname-db;Port=5432;Database=surname;Username=postgres;Password=postgres
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_Audience}
      - RabbitMQOptions__Host=rabbitmq
      - RabbitMQOptions__Port=${RABBITMQ_PORT}
      - RabbitMQOptions__Username=${RABBITMQ_USER}
      - RabbitMQOptions__Password=${RABBITMQ_PASS}
    ports: [ "5003:8080" ]
    depends_on:
      rabbitmq:
        condition: service_healthy 
      surname-db:
        condition: service_healthy